# Generated by Django 3.1.3 on 2020-11-19 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(default='这个人很懒，什么都没有写！')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.users')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.types')),
            ],
        ),
    ]
